### ISSUE TITLE
DSM7 PLEX_PREFERENCES_FILE path is incorrect

### ISSUE THREAD

**Issue by programatix** [YuriyGuts/syno-plex-update#1]
In DSM7, the path for ```PLEX_PREFERENCES_FILE``` is ```'/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server'```

On package trust, how did you add the certificate? DSM7 Package Center has no "Certificate" tab as in DSM6.

**Comment by programatix** [comment]
Additionally the version comparison should use the ">" instead of "!=" as now, if older version is found on the server, the script assume that there is an update.

**Comment by programatix** [comment]
Resolved in https://github.com/YuriyGuts/syno-plex-update/commit/e844a00fe80fab6d49bceca3db578527a996b246

**Comment by YuriyGuts** [comment]
Thank you for the PR (https://github.com/YuriyGuts/syno-plex-update/pull/2) 👍 

> On package trust, how did you add the certificate? DSM7 Package Center has no "Certificate" tab as in DSM6.

Interesting— I _think_ my DSM 7 had this setting somewhere after upgrading from DSM 6, but maybe it was removed later. I can't find it either.

According to https://www.reddit.com/r/synology/comments/os7xlx/add_third_party_cert_keys_to_dsm7/ it seems like importing the key is no longer necessary.

**Comment by programatix** [comment]
Will try the script on the next Plex update and report in.

**Comment by programatix** [comment]
I confirmed that in DSM 7, the installation works without the need of adding the package trust in DSM 6.

**Comment by YuriyGuts** [comment]
Thanks for the heads up!
