### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by tayzer522** [YuriyGuts/syno-plex-update#12]
I'm getting a permission denied error when attempting to run the scheduled task manually.
`bash: /volume1/Scripts/syno-plex-update.sh: Permission denied`
[output.log](https://github.com/YuriyGuts/syno-plex-update/files/9760729/output.log)

**Comment by YuriyGuts** [comment]
- Is the scheduled task set up to run on behalf of the `root` user? (Edit task -> General settings -> User)
- What are the file permissions/ownership records on the script? (`ls -la /volume1/Scripts/syno-plex-update.sh`)

**Comment by tayzer522** [comment]
Changing to run as `root` fixed it. Thank you kindly!
