### ISSUE TITLE
Plex package stopped occasionally

### ISSUE THREAD

**Issue by tillkruss** [YuriyGuts/syno-plex-update#5]
Every couple of days the Plex package is stopped after running this script every night.

I just log in a hit Run. Any way to make sure the script re-starts it if necessary?

**Comment by YuriyGuts** [comment]
Strange; I've been using the script for more than a year (nightly) and I don't recall ever experiencing this. Do the stoppages happen during the day or immediately after the auto-update cycle?

I'd suggest enabling logs on the Plex Server itself and looking into them when the server stops again. Additionally, I'd try disabling the script for some time to see if using it correlates with occurrences of the issue.

Another workaround might be to create another scheduled task that just runs `synopkg start PlexMediaServer` on a regular basis.

**Comment by tillkruss** [comment]
I'm gonna wait for the next update and see if that caused it. Thanks for all the tips!
