### ISSUE TITLE
Download Plex Pass Versions

### ISSUE THREAD

**Issue by madxcream** [YuriyGuts/syno-plex-update#8]
Hi, I noticed it's not grabbing the Plex Pass version available. Is there a way to have it download those?

**Comment by YuriyGuts** [comment]
Hi! It should be possible by design, and some code was contributed by another user for this (https://github.com/YuriyGuts/syno-plex-update/blob/master/syno-plex-update.sh#L84). Unfortunately, I don't have a Plex Pass, so I can't verify it. Fixes are welcome though.

**Comment by tillkruss** [comment]
How can I set the update channel?

**Comment by madxcream** [comment]
Ok, I had thought I had this set up in Plex already. If you have PlexPass, you can go into Plex, Settings, General and change the Server Update Channel to Beta instead of Public. Then it'll download the PlexPass versions.
